version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: c7-cbc
    volumes:
      - ./data:/work/source/
    # 以下のエラーに対応するために追記
    # D-Bus connection: Operation not permitted
